### ISSUE TITLE
New updated jbnc can't send PRIVMSG's

### ISSUE THREAD

**Issue by nirvanaxo** [toc-irc/jbnc#26]
older bugs dont crash though, but /joining #x:x or anything with a : in it causes jbnc to act differently; won't send your JOIN when you connect/join - still forwards you messages though

**Comment by Madriix** [comment]
As soon as I type "/join #x:x" on UnrealIRCd 5.0.5.1, I get this response:

>  [05:39:21] * #x:x Cannot join channel: Channel name contains illegal characters (must be valid UTF8)


It works on ircd-seven-1.1.9, idem on InspIRCd-3

**Comment by nirvanaxo** [comment]
hmm, we're on charybdis on irc.imperialfamily.com - when sending messages it won't go through:
test here: miami.letstoc.com
