### ISSUE TITLE
[FEAT REQUEST] auto-op/voice clients when they're opped/voiced, remove when they're deopped/devoice

### ISSUE THREAD

**Issue by MRNFN80** [toc-irc/jbnc#5]
[FEAT REQUEST] auto-op/voice clients when they're opped/voiced, remove when they're deopped/devoice
so if anybody / somebody ops, halfops, or voices somebody it adds their *!ident@fullhostname to auto-op
if somebody deoped / devoices / dehalfops them then any masks involving that target usser is removed for that mode

- add users to autoop / avoice / ahalfop when +o/v/h is set
- remove users from autoop / avoice / ahalfop when -o/v/h is set

**Comment by MRNFN80** [comment]
and on by default
/jbnc autoop off
/jbnc autohalfop off
/jbnc autovoice off
to turn them off :O

**Comment by realrasengan** [comment]
Adds aop/aov/aoh for nicks
https://github.com/toc-irc/jbnc/commit/a178ce4926c4db04bf4f8b5b3366cb88fb3881f6

Adds userhost as the controller if userhost-in-names is available (IRCv3)
https://github.com/toc-irc/jbnc/commit/495dbf29ba9a18af74761a84137e3b9d5d23ed90
