### ISSUE TITLE
When logging on with webchat

### ISSUE THREAD

**Issue by MRNFN80** [toc-irc/jbnc#6]
in mIRC in every channel I see:
12:12pm * mrinfinity sets mode: 

in Webchat I see:
12:12 *** mrinfinity (mrinfinity@291fe5) has joined the channel
12:12 *** Channel mode is +
12:12 *** The topic is: <#netops> NETWORK ops channel for IRCops that lead their communities. Paving a decentralized foundation for the *<THEALL> | sysadmin doc: https://docs.google.com/document/d/1m6rZE5zMQkjJVksgAyb67WgNgYIb01H5f-cGnaqoPb0/edit?usp=sharing
12:12 *** Topic set by mrinfinity on 15 April 2020, 21:32:58
12:12 *** Channel mode is +nst 

Node the channel mode is + line

**Comment by realrasengan** [comment]
This should be fixed with latest commit.
