### ISSUE TITLE
[REQUEST] For binding to certain IP addresses 

### ISSUE THREAD

**Issue by MRNFN80** [toc-irc/jbnc#8]
[REQUEST] For binding to certain IP addresses on multi-homed boxes. Currently listens on all available IP addresses

**Comment by realrasengan** [comment]
https://github.com/toc-irc/jbnc/commit/91aba1bd7b29a922a02dcb8e6d5180f9b3bea73a

Use "bouncerIp" in config like "bouncerIp":"1.2.3.4" or "bouncerIp":null for all ips.
